# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cht < Formula
  desc "A command-line tool to display cheatsheets."
  homepage "https://github.com/vvision/cht"
  version "1.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/vvision/cht/releases/download/v1.1.0/cht_1.1.0_darwin_amd64.tar.gz"
      sha256 "17c1e5c30e76bd11bb79e1f511e830b4410a4790ff2c07f920507f99e731c82e"

      def install
        bin.install "cht"
      end
    end
    on_arm do
      url "https://github.com/vvision/cht/releases/download/v1.1.0/cht_1.1.0_darwin_arm64.tar.gz"
      sha256 "c01c97cd6334ad016704a4f7e87a726fbc39a393f1e073c11b9b0740da6fe5aa"

      def install
        bin.install "cht"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vvision/cht/releases/download/v1.1.0/cht_1.1.0_linux_amd64.tar.gz"
        sha256 "27801d75b54000af7f23375a318971b2b007a93201559b641e9584faa74ccc5e"

        def install
          bin.install "cht"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vvision/cht/releases/download/v1.1.0/cht_1.1.0_linux_arm64.tar.gz"
        sha256 "f4b6f0f8a3581e1687de7cbee0da08745c46c5dc802a5283bc5c22505f8b8b67"

        def install
          bin.install "cht"
        end
      end
    end
  end
end
