# This file was generated by GoReleaser. DO NOT EDIT.
cask "cht" do
  name "cht"
  desc "A command-line tool to display cheatsheets."
  homepage "https://github.com/vvision/cht"
  version "1.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cht"

  on_macos do
    on_intel do
      url "https://github.com/vvision/cht/releases/download/v#{version}/cht_#{version}_darwin_amd64.tar.gz"
      sha256 "c094d6e747a83b499f5abe88d5edd03dc6c4fd951e4080675cabcd09d222a404"
    end
    on_arm do
      url "https://github.com/vvision/cht/releases/download/v#{version}/cht_#{version}_darwin_arm64.tar.gz"
      sha256 "cb3e964feb3ad404c6be54abf0d1e374a5472068f6e51e4e877a03a174a5760f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/vvision/cht/releases/download/v#{version}/cht_#{version}_linux_amd64.tar.gz"
      sha256 "5517f9205059992a7b39e4bb76ea4e7b9bac30bdebf95d34767f7976dc0c9aa9"
    end
    on_arm do
      url "https://github.com/vvision/cht/releases/download/v#{version}/cht_#{version}_linux_arm64.tar.gz"
      sha256 "d2cc833a3309e64fdec4c88e53fa6a1a2412390eedf658ec846b6ea5bbd10ee9"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cht"]
  end

  # No zap stanza required
end
