# This file was generated by GoReleaser. DO NOT EDIT.
cask "cht" do
  name "cht"
  desc "Command-line tool to display cheatsheets"
  homepage "https://github.com/vvision/cht"
  version "1.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cht"

  on_macos do
    on_intel do
      url "https://github.com/vvision/cht/releases/download/v#{version}/cht_#{version}_darwin_amd64.tar.gz"
      sha256 "fe19cc7ef25151e686e39a92dd2e2088a490cf84237a368ad27338817cbf5923"
    end
    on_arm do
      url "https://github.com/vvision/cht/releases/download/v#{version}/cht_#{version}_darwin_arm64.tar.gz"
      sha256 "0393ac44444a9b4b54a5677b03d0bb56e7b57c04b8f3ae949c799234cb94ce59"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/vvision/cht/releases/download/v#{version}/cht_#{version}_linux_amd64.tar.gz"
      sha256 "eaf51066e05451ff6ae31b2d0c5e3bb1250e89f9502a60337c25279e822b7b97"
    end
    on_arm do
      url "https://github.com/vvision/cht/releases/download/v#{version}/cht_#{version}_linux_arm64.tar.gz"
      sha256 "9bd0ae2836819bb4d1c6ee5bec918a67656c22c0cdd176ba1d3698517165fa7e"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cht"]
  end

  # No zap stanza required
end
