# This file was generated by GoReleaser. DO NOT EDIT.
cask "cht" do
  name "cht"
  desc "Command-line tool to display cheatsheets"
  homepage "https://github.com/vvision/cht"
  version "1.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cht"

  on_macos do
    on_intel do
      url "https://github.com/vvision/cht/releases/download/v#{version}/cht_#{version}_darwin_amd64.tar.gz"
      sha256 "b1b55f4d53b7de87df7e266988d2fd97287f882f23eb02039588aea482a86a5e"
    end
    on_arm do
      url "https://github.com/vvision/cht/releases/download/v#{version}/cht_#{version}_darwin_arm64.tar.gz"
      sha256 "51e8c07ad974fd6839c45c65056e73ebe978c2d5f668842673577c30abdc617c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/vvision/cht/releases/download/v#{version}/cht_#{version}_linux_amd64.tar.gz"
      sha256 "536e1cb4eaf13c520ef73e3426f3a33aafa1a57f190d22cd3e9f7a25196f65fc"
    end
    on_arm do
      url "https://github.com/vvision/cht/releases/download/v#{version}/cht_#{version}_linux_arm64.tar.gz"
      sha256 "44fca523a132a287b57869a31affadce68bbcff00dcc89234c3dec61f7364644"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cht"]
    end
  end

  # No zap stanza required
end
