# This file was generated by GoReleaser. DO NOT EDIT.
cask "dtfs" do
  name "dtfs"
  desc "Modern, cross-platform dotfiles manager"
  homepage "https://github.com/vvision/dtfs"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dtfs"

  on_macos do
    on_intel do
      url "https://github.com/vvision/dtfs/releases/download/v#{version}/dtfs_#{version}_darwin_amd64.tar.gz"
      sha256 "ee6698079788f241b1818c585a54f5795ebb0c7a3e2f7dd17207857bef4a90e9"
    end
    on_arm do
      url "https://github.com/vvision/dtfs/releases/download/v#{version}/dtfs_#{version}_darwin_arm64.tar.gz"
      sha256 "9c40e319d56e533e42ba712effe890fd450ebc99b9e592f632df40cd87e7ca5b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/vvision/dtfs/releases/download/v#{version}/dtfs_#{version}_linux_amd64.tar.gz"
      sha256 "944058be26dea8a56298c9a41cbeb21ce0305b71cd431dcec1cb23d743e9eb0a"
    end
    on_arm do
      url "https://github.com/vvision/dtfs/releases/download/v#{version}/dtfs_#{version}_linux_arm64.tar.gz"
      sha256 "8b7bf3007b3082f941c874803f17d9d3576b331a88b8246af9656cde5ad9522a"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dtfs"]
    end
  end

  # No zap stanza required
end
